name: Order Service Tests

on: [push, pull_request]

jobs:
  build:
    name: Run Spring Boot Tests
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.3.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: orderservice
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B clean verify --file order-service/pom.xml